apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-west-1

availabilityZones:
- eu-west-1a
- eu-west-1b
- eu-west-1c

vpc:
  id: vpc-060a92980c16c332e
  subnets:
    private:
      eu-west-1a:
        id: subnet-015ba9a2c0bc2f2ed
      eu-west-1b:
        id: subnet-0bf2939858292d2a4
      eu-west-1c:
        id: subnet-0ff3cc9def8f991da
  clusterEndpoints:
    publicAccess:  false
    privateAccess: true

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 1
    privateNetworking: true

  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 1
    privateNetworking: true

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    logRetentionInDays: 7